### ISSUE TITLE
java.lang.VerifyError: com/box/boxjavalibv2/jsonparsing/BoxJSONParser

### ISSUE THREAD

**Issue by mkmcsa** [box/box-android-sdk-v2#107]
Hi, 

I am getting following error while authenticating .   Any help will greatly be appreciated.. 

    java.lang.VerifyError: com/box/boxjavalibv2/jsonparsing/BoxJSONParser
            at com.box.boxjavalibv2.BoxClient.createJSONParser(BoxClient.java:564)
            at com.box.boxjavalibv2.BoxClient.<init>(BoxClient.java:158)
            at com.box.boxjavalibv2.BoxClient.<init>(BoxClient.java:138)
            at com.box.boxandroidlibv2.BoxAndroidClient.<init>(BoxAndroidClient.java:58)
            at com.box.boxandroidlibv2.activities.OAuthActivity.createBoxClientForOAuth(OAuthActivity.java:73)
            at com.box.boxandroidlibv2.activities.OAuthActivity.startOAuth(OAuthActivity.java:65)
            at com.box.boxandroidlibv2.activities.OAuthActivity.onCreate(OAuthActivity.java:52)
            at android.app.Activity.performCreate(Activity.java:5451)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2389)
            at android.app.ActivityThread.access$900(ActivityThread.java:169)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1277)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5479)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by chitransh01** [comment]
Hi,

The same issue i was facing because i have added BoxJavaLibraryV2 in my al sample instead of BoxAndroidLibraryV2.

Import again both the libraries & added BoxJavaLibraryV2 project in build path of BoxAndroidLibraryV2 then added BoxAndroidLibraryV2 as a library in my sample project Properties>Android>Library>Add.

Done !!!

Thanks :)
